spring.application.name=backend

spring.datasource.url=jdbc:postgresql://postgres:5432/e_ticket_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

jwt.secret=E_Ticket_Jwt_Secret_Key_Mustafa_Ilter_2026_Very_Secure
jwt.access-token-expiration=2592000000